/**
 * WebAPI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Address } from './address';

export interface Customer { 
    id: string;
    firstName?: string;
    lastName?: string;
    address?: Address;
    addressId?: string;
    email?: string;
    phoneNumber?: string;
}