/**
 * WebAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type DeliveryType = 0 | 1 | 2;

export const DeliveryType = {
    NUMBER_0: 0 as DeliveryType,
    NUMBER_1: 1 as DeliveryType,
    NUMBER_2: 2 as DeliveryType
};

