/**
 * WebAPI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Repairment } from './repairment';

export interface Employee { 
    id: string;
    firstName?: string;
    lastName?: string;
    createdDate?: Date;
    isAdmin?: boolean;
    email?: string;
    password?: string;
    repairments?: Array<Repairment>;
}