/**
 * WebAPI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { PaymentType } from './paymentType';
import { Repairment } from './repairment';

export interface Payment { 
    id?: string;
    value?: number;
    repairmentId?: string;
    repairment?: Repairment;
    createdDate?: Date;
    type?: PaymentType;
    isDeleted?: boolean;
    remarks?: string;
}