/**
 * WebAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Repairment } from './repairment';
import { PaymentType } from './paymentType';


export interface Payment { 
    id?: string;
    value?: number;
    repairmentId?: string;
    repairment?: Repairment;
    createdDate?: string;
    type?: PaymentType;
    isDeleted?: boolean;
    remarks?: string | null;
}

